### ISSUE TITLE
Check create operations in lib-datahandler

### ISSUE THREAD

**Issue by mcjaeger** [sw360/sw360portal#106]
Create can be done by anyone, like any user can create components, projects. But a user cannot create licenses. This is done in the portlet level, however, could be also moved to the backend and in the lib-datahandler.

**Comment by mcjaeger** [comment]
issue could be solved, as done with other calls, by passing the user as argument at the license creation call, requires the big picture to the how to secure API calls to make this understandable how to access the thrift API in a secure way

**Comment by maximilianhuber** [comment]
> However, the big picture about "how to secure API calls" would be important input here.

see #218

**Comment by mcjaeger** [comment]
for licenses it shall be also clearing admin who can create licenses.

**Comment by alex-evo** [comment]
clearing admins can create licenses already

**Comment by alex-evo** [comment]
Actually, LicenseDatabaseHandler also already gets the user argument and checks for permissions before creating/updating licenses. I guess this issue is too old and does not reflect the current state.

What's left insecure are the methods used for bulk import of licenses from files. This is done in ComponentImportPortlet and in the executable class LicenseImporter - do we need it at all? I'm tempted to delete it
