### ISSUE TITLE
IE11: Problem when deleting a project or component

### ISSUE THREAD

**Issue by stefanjaeger-evo** [sw360/sw360portal#122]
1. login as user@sw360.org
2. Add a new project or component
3. search for the project or component with keyword search, press delete icon under Actions column and confirm OK
4. Message “I could not delete the project!” is displayed, press OK
5. Click on project name, message “Project is temporarily unavailable.” is displayed
6. Click on Projects tab to refresh the page, deleted project is not in the list anymore.

Same for component.

same for attachment:
1. Go to Attachments page of an existing release of a component
2. Click on delete icon for one of the attachments
3. Message “I could not remove the attachment!” is displayed
4. Go back to component, then release overview, open the release and attachments page (or refresh the page). Attachment was actually removed.

**Comment by heydenreich** [comment]
I checked the first part: in Chromium and Firefox it works fine for projects and components - the document is deleted when I click the delete-icon. (Did you use IE by any chance?)

For the second part: in the current SW360-version, there is no delete-icon at the details-view of the attachments any more. So the only place with delete-icon is the attachments - edit view. Here again, I cannot verify the above issue, deleting works fine.

Are you sure that you used the same user for creating the documents and deleting? Otherwise, you might get the moderation-issue (which is fixed in one of the current pull-requests).

**Comment by sw360-blue-developer** [comment]
yes, good point, I tested it with FF and it works.. IE11 is not working..

**Comment by mcjaeger** [comment]
please contribute fix if you find this should find its way in master
