### ISSUE TITLE
New Line in Project Description Text

### ISSUE THREAD

**Issue by mcjaeger** [sw360/sw360portal#152]
If there is a new line in the description text (just hit return key in the description field when editing it): The table view will fail - see screenshot below. In Firefox Web console, clicking on the line with the error will display the JSON array with the entry that caused the error.

It must be checked if the entered return is also leading to the same error (and fixed). Fix could be that for display in the table, all returns are cleaned out.

![036 oss sw360 20160422 screenshot proejct with errornous description fail](https://cloud.githubusercontent.com/assets/3418977/14740024/06a7aa76-088c-11e6-9932-fc40c8eb710f.png)

**Comment by alex-evo** [comment]
I suspect that this can be fixed by wrapping the values with backticks instead of quotes in the generated javascript that populates the table. If this fix works, it should be applied consistently across all places where a table is populated in this way.
Also to be considered: whether it's possible to populate the tables in HTML instead of javascript as it's safer in this regard.
