### ISSUE TITLE
Names for search fields confusing

### ISSUE THREAD

**Issue by mcjaeger** [sw360/sw360portal#212]
There are two main search fields titles that could be renamed to reduce user confusion:

* Name search: it searches actually for other fields as well, not just the name, should be renamed to '_Any field starts with:_' (components only)
* Keyword search: it not seem to search for keywords (which is not precisely known), but seems to search or the string matched name only: '_Name starts with:_' (projects and components)

Rename also the main search entry label "keyword search" to "Any field starts with:"

**Comment by alex-evo** [comment]
as discussed, the following will be changed:
- Keyword Search will be renamed to Display Filter
- Keyword Search at projects and components will be renamed to Display Filter by Name
- Filter by Project Name at projects will be changed so that it searches a substring of project name
- Name Search at components will be changed so that it searches a substring of component name
