### ISSUE TITLE
Concept for Thrift Authentication, authorization and securing

### ISSUE THREAD

**Issue by maximilianhuber** [sw360/sw360portal#218]
Currently all thrift services trust their callers and do not ask for authentication or authorization. Further is the protocol currently using cleartext transport. (since it is on the same server from Java to Java)

This is fine within a trusted net but introduces problem once one distributes the services on multiple servers or makes the our services accessible for external  services.
#### There are multiple ideas how this could be secured:
1. Add another service which translates the internal thrift to an external protocol (e.g. REST) which adds the necessary changes to secure the connections and requests
2. Modify the thrift services, servers and clients
   - to have authentication and authorization [1], which uses some backend service or liferay, and
   - to add SSL/TLS for an encrpyted transport [2].
3. More discussion has already been made, which is not yet fully reproduced in this text
## Goal of this issue to define what needs to be implemented.

[1] http://web.ist.utl.pt/ist177062/Thrift_Auth.html
[2] http://www.doublecloud.org/2014/01/securing-thrift-traffic-uncommon-but-important-use-case/

**Comment by mcjaeger** [comment]
(from discussion)

one point: actually would lead to an entire day of discussion. My question would be, if we need the thrift services then, when we build another REST client interface in addition, because Thrift has an advantage supporting different programming languages - like used is different client.

another point: the thrift as build now represents also the data model definition, so having thrift there has already some usage. In addition, the thrift IDL defines also the service, would be good to have maybe the REST services generated from this?

**Comment by bufferoverflow** [comment]
We use a string `authToken` for each service as first parameter on our environment, this allows us the verify access at services level on server side.

**Comment by maximilianhuber** [comment]
One might want to have a look at the function `String authToken=AuthTokenUtil.getToken(PortalUtil.getHttpServletRequest(renderRequest));` (see https://muralie39.wordpress.com/2014/06/22/authentication-token-in-liferay/). But this looks like that it is bound to portlets and renderRequests. It might be complicated to use this for abstract service requests.

**Comment by mcjaeger** [comment]
is now re-picked-up with the sw360rest project
