### ISSUE TITLE
Add clearing_admin and admin for moderation requests

### ISSUE THREAD

**Issue by mcjaeger** [sw360/sw360portal#240]
For the moderation requests, they are routed to the moderators and the creator. However, it should be also that

* for projects, clearing admin with same group membership should receive a moderation request as well. also the admin of the sw360 should receive the moderation request
* for components and releases, clearing admin and admin should receive moderation requests as well.

**Comment by heydenreich** [comment]
@mcjaeger :
Do I understand it correctly?
_for projects:_ 
* add clearing admin of same group to moderators
* add all admins (no matter what group) to moderators (c.f.: with licenses we only use the admins of the respective group)
* the case that there is no moderator is irrelevant no matter what we do with admins, since we always have the creator

_ for components and releases:_
* add all clearing admins and admins no matter what group (or only of the same group? or same as with projects?)

**Comment by mcjaeger** [comment]
For components and releases: add clearing admins of the group (department) of the creator of component or release. If no clearing admin is present for that group (department) then admin only.

**Comment by heydenreich** [comment]
Consensus:
for projects:

* add clearing admin of same group to moderators
add all admins (no matter what group) to moderators (c.f.: with licenses we only use the * * admins of the respective group)
* the case that there is no moderator is irrelevant no matter what we do with admins, since we always have the creator

for components and releases:

same as above but use department of creator as department
