### ISSUE TITLE
View not refreshed automatically when deleting a release

### ISSUE THREAD

**Issue by adrian-evo** [sw360/sw360portal#268]
When deleting a release from Release Overview list, the message "Do you really want..." appears, and when clicking OKAY, the deleted release is still listed among other releases (i.e. view not refreshed). When deleting a component, attachment, etc., the views are refreshed automatically.

**Comment by alex-evo** [comment]
The problem is that the JavaScript code that removes the row is defined in clearingStatus.jspf and uses the reference `oTable` to refer to the table where the row should be deleted. Unfortunately, this reference is overwritten by the vulnerabilities table.
We have to ensure throughout the code that the JS variables for tables in different jsps and jspfs are unique.
Also need to check whether the problem with pagination applied to this table and others (see #271)

**Comment by alex-evo** [comment]
the issue is a duplicate to #232
