### ISSUE TITLE
Ask ektorp project to merge branch 201

### ISSUE THREAD

**Issue by mcjaeger** [sw360/sw360portal#302]
I think it is fine what we did with

https://github.com/sw360/sw360portal/pull/300

A more sustainable solution on the long run would be to merge this branch 201 in the ektorp project. we should contact them and see if we can do something.

**Comment by maximilianhuber** [comment]
I have already talked to the maintainer of ektorp. The branch 201 is already merged on 16 Sep 2014 but there was only one release after org.ektorp.parent-1.4.2 of 8 May 2014 and that was not uploaded to maven central.

The maintainer suggested to use something like `https://jitpack.io/#helun/Ektorp` to get the release 1.4.3 directly from github instead of maven central.

I suggest closing this issue.

**Comment by mcjaeger** [comment]
suggest to change: use jitpack in pom file and let's go to 1.4.3 and long term: we should drop ektorp.

**Comment by maximilianhuber** [comment]
@mcjaeger @alex-evo there is a new release of ektorp (1.4.4 (14.3.2017)) on maven-central. We now can update to the current version of ektorp!
