### ISSUE TITLE
List view for attachments needs rework

### ISSUE THREAD

**Issue by mcjaeger** [sw360/sw360portal#454]
The list view needs improvements:

* it has odd use of space,
* multi-row, multi column view looks difficult to catch important information,
* no sorting possible
* some information (approver comment) could be displayed at mouse over only?
* File size is missing.
* approved attachments shall have some indications (use of colour?) to let the user quickly see approved attachments

**Comment by mcjaeger** [comment]
pls find some proposals how it could look like considering the unfold idea ...

Note that the bottommost bubble is a little bit slipped down.

![036 oss sw360 20170712 screenshot tech ui mockup uploads 01](https://user-images.githubusercontent.com/3418977/28123573-96e46846-6721-11e7-9634-af0250229fe3.png)

![036 oss sw360 20170712 screenshot tech ui mockup uploads 02](https://user-images.githubusercontent.com/3418977/28123584-9cfb74fe-6721-11e7-903f-1f446f393588.png)

**Comment by imaykay** [comment]
@mcjaeger some questions regarding this rework:
* "Download All" button gone. Not necessary anymore?
* "Status" column missing compared to old table. Not necessary anymore?
* Is there a common abbreviations list for the "type" data? 
* Shall we switch team and email columns so that they are next to each other. Short uploader emails make their team standing closer to the approver email.
* Only download action available today. Others only in edit mode. Should they really be available in view mode?
* Missing information in the data model right now - load them from somewhere or use columns to display other values:
** Size
** Usage
* We would get two functionalities for free from jquery datatables above the table. Remove it or keep it?
** page size drop down
** search field to filter the table

<img width="1212" alt="attachmentsdetailtable_new" src="https://user-images.githubusercontent.com/27430165/28267811-0a4e20c8-6afc-11e7-9ab4-c66be97d2612.png">

**Comment by mcjaeger** [comment]
uff, OK, to answer the questions
* lets keep download all in, was accident
* Status: I thought it would be implicit by having the approval column filled out but that was maybe too fast, because it can be rejected? How about making the email of approving user greeen and rejecting user red?
* Abbreviations: yes, had the same idea and I started it, like .doc .spdx .cli but it was too difficult. Shall I come up with these?
* Edit could lead maybe to a pop up dialogue which allows the user to edit the fields? or the user could edit the fileds directly in the current view?
* we need a migration script and a data conversion script for size and usage. I am inclined towards of keeping size and usage out in the first attempt. @maximilianhuber @alexbrdn what do you think?
* adding filter is good
* adding paging could be good, largest list has had about 25 entries as far as I have seen. maybe not necessary, but with a better attachments table, maybe people upload more attachments.

**Comment by imaykay** [comment]
Allright, pull request #508 should look like this:

<img width="1600" alt="grafik" src="https://user-images.githubusercontent.com/27430165/28371768-2374f09c-6c9e-11e7-8fa1-bddb39af6602.png">

Additional remarks:
* abbreviated file types and every field with ellipsis has a tooltip containing the complete text
* actions are kept like today - so only download available. Edit and Delete should be implemented in an own story as they might need some effort
* same for new data size and usage
